name: Auto Check-in

on:
  schedule:
    # 16:15(UTC+8)
    - cron: '15 16 * * *'

jobs:

  airport:
    runs-on: ubuntu-latest
    container: autorip/python-slim:requests
    steps:
      - uses: actions/checkout@v2
      - name: airport check in
        env:
          airport_host: ${{ secrets.AIRPORT_HOST }}
          airport_account: ${{ secrets.AIRPORT_ACCOUNT }}
          airport_account_pwd: ${{ secrets.AIRPORT_ACCOUNT_PWD }}
        run: python airport.py $airport_host $airport_account $airport_account_pwd

  game1:
    runs-on: ubuntu-latest
    container: autorip/python-slim:requests
    steps:
      - uses: actions/checkout@v2
      - name: game check in
        env:
          game_host: ${{ secrets.GAME_HOST }}
          game_id: ${{ secrets.GAME_ID }}
        run: python game.py $game_host $game_id

  game2:
    runs-on: ubuntu-latest
    container: autorip/python-slim:requests
    steps:
      - uses: actions/checkout@v2
      - name: game check in
        env:
          game_host: ${{ secrets.GAME_HOST }}
          game_id_2: ${{ secrets.GAME_ID_2 }}
        run: python game.py $game_host $game_id_2
